# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/AOften/Computer Organization and Design/lab/vivado1/addsub/addsub.cache/wt} [current_project]
set_property parent.project_path {E:/AOften/Computer Organization and Design/lab/vivado1/addsub/addsub.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {{E:/AOften/Computer Organization and Design/lab/vivado1/vivado1/student/addsub8/addsub8.v}}
read_xdc {{E:/AOften/Computer Organization and Design/lab/vivado1/addsub/addsub.srcs/constrs_1/new/add4_pin.xdc}}
set_property used_in_implementation false [get_files {{E:/AOften/Computer Organization and Design/lab/vivado1/addsub/addsub.srcs/constrs_1/new/add4_pin.xdc}}]

synth_design -top addsub8 -part xc7a35tcpg236-1
write_checkpoint -noxdef addsub8.dcp
catch { report_utilization -file addsub8_utilization_synth.rpt -pb addsub8_utilization_synth.pb }
