# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.cache/wt} [current_project]
set_property parent.project_path {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{e:/AOften/Computer Organization and Design/lab/vivado6/1.coe}}
add_files -quiet {{E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.runs/InstructionROM_synth_1/InstructionROM.dcp}}
set_property used_in_implementation false [get_files {{E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.runs/InstructionROM_synth_1/InstructionROM.dcp}}]
read_verilog -library xil_defaultlib {
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/DataRAM.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/RegisterFiles.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/CtrlUnit.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/adder_32bits.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/adder_if.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/ALU.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/and_1bit.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/MEM.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/ID.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/flipflop.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/EX.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/IF.v}
  {E:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/new/MipsPipelineCPU.v}
}
synth_design -top MipsPipelineCPU -part xc7a35tcpg236-1
write_checkpoint -noxdef MipsPipelineCPU.dcp
catch { report_utilization -file MipsPipelineCPU_utilization_synth.rpt -pb MipsPipelineCPU_utilization_synth.pb }
