# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/ip/InstructionROM_1/InstructionROM.xci
# IP: The module: 'InstructionROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/ip/InstructionROM_1/InstructionROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstructionROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/ip/InstructionROM_1/InstructionROM.xci
# IP: The module: 'InstructionROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AOften/Computer Organization and Design/lab/vivado6/Pipelining/Pipelining.srcs/sources_1/ip/InstructionROM_1/InstructionROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstructionROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
